parameters:
  env(DATABASE_HOST): localhost
  env(DATABASE_USER): root
  env(DATABASE_PASSWORD): secret
  env(DATABASE_PORT): 3306

doctrine:
    dbal:
        # configure these for your database server
        server_version: "5.7"
        driver:   pdo_mysql
        host:     "%env(DATABASE_HOST)%"
        port:     "%env(DATABASE_PORT)%"
        dbname:   wholesale
        user:     "%env(DATABASE_USER)%"
        password: "%env(DATABASE_PASSWORD)%"
        charset:  utf8mb4
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
