version: '3.4'
services:
  nginx:
    container_name: wholesale_nginx
    image: nginx:latest
    volumes:
      - ./:/var/www/wholesale
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8010:80

  php:
    container_name: wholesale_php
    build: ./docker/php
    volumes:
      - ./:/var/www/wholesale
    working_dir: /var/www/wholesale

  db:
    container_name: wholesale_db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
    expose:
      - "3306"
    ports:
      - 3307:3306

  redis:
    container_name: wholesale_redis
    image: redis