# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

    app.upload.dir: '%kernel.project_dir%/public/upload'
    app.download.dir: '%kernel.project_dir%/public/download'

    app.reader.schema.remains:
       - name: !php/const App\Schema::NAME
         fieldIndex: 1
         fieldType: string

       - name: !php/const App\Schema::SKU
         fieldIndex: 1
         fieldType: string

       - name: !php/const App\Schema::SELLER_COST
         fieldIndex: 4
         fieldType: float

       - name: !php/const App\Schema::QUANTITY
         fieldIndex: 2
         fieldType: int

    app.reader.schema.hotline:
       - name: !php/const App\Schema::SKU
         fieldIndex: 10
         fieldType: int

       - name: !php/const App\Schema::RETAIL_PRICE
         fieldIndex: 5
         fieldType: float

    app.writer.schema.default:
        A: !php/const App\Schema::SKU
        B: !php/const App\Schema::NAME
        C: !php/const App\Schema::WHOLESALE_PRICE
        D: !php/const App\Schema::QUANTITY
        E: !php/const App\Schema::SELLER_COST
        F: !php/const App\Schema::RETAIL_PRICE



services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Spreadsheet
    Yectep\PhpSpreadsheetBundle\Factory: '@phpoffice.spreadsheet'

    # Lexik converter
    Lexik\Bundle\CurrencyBundle\Currency\Converter: '@lexik_currency.converter'
    Lexik\Bundle\CurrencyBundle\Command\ImportCurrencyCommand: ~

    # Gedmo doctrine extensions
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]



    # Application

    App\Service\SkuFinder: ~
    App\Service\FileUploader:
        arguments: ['%app.upload.dir%']

    App\Processor\Processor:
        arguments:
            $uploadPath: '%app.upload.dir%'
            $downloadPath: '%app.download.dir%'

    App\Reader\RemainsReader:
        calls:
          - [ setSchema, ['%app.reader.schema.remains%'] ]

    App\Reader\HotlineReader:
        calls:
          - [ setSchema, ['%app.reader.schema.hotline%'] ]

    App\Writer\FileWriter:
        arguments:
          $schema: '%app.writer.schema.default%'

    App\Processor\PriceStrategy\PriceStrategyInterface: '@App\Processor\PriceStrategy\InRangeStrategy'
    App\Processor\PriceStrategy\InRangeStrategy: ~


    App\Form\Extension\HelpMessageTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    App\EventListener\Doctrine\JobRemoveSubscriber:
        arguments:
            $uploadPath: '%app.upload.dir%'
            $downloadPath: '%app.download.dir%'
        tags:
            - { name: doctrine.event_subscriber }